import userRouter from "./userRoute.js";
import supplierRouter from "./supplierRoute.js";
import orderRouter from "./orderRouter.js";
import productRouter from "./productRoute.js";
import schedulerRouter from "./schedulerRouter.js";
import incomeExpRouter from "./incomeExpRouts.js";
import supOrdDetailsRouter from "./supOrdDetailsRouter.js";
import masterRouter from "./masterRoute.js";
import uploadRouter from "./uploadRoute.js";
import dashboardRouter from "./dashboardRoute.js";
import authRouter from "./authRoute.js";
import coastRouter from "./coastRoute.js";
import laborPriceRouter from "./laborPriceRoute.js";
import diamondMasterRouter from "./diamondMasterRoute.js";
import pricingProductRouter from "./pricingProductRoute.js";
import partnerRouter from "./partnerRoute.js";
import assetRouter from "./assetRoute.js";
import targetRouter from "./targetRoute.js";
import mediatorRouter from "./mediatorRouter.js";
import paymentRouter from "./paymentRouter.js";
import roleRouter from "./roleRoute.js";
import permissionRouter from "./permissionRoute.js";
import panelUserRouter from "./panelUserRoute.js";
import loginSessionRouter from "./loginSessionRoute.js";
import backupRouter from "./backupRoutes.js";
import customerImportRoute from "./customerImportRoute.js";
import employeeRouter from "./employeeRoute.js";
import salaryRouter from "./salaryRoute.js";
import stockRouter from "./stockRouter.js";
import crmRouter from "./crmRoute.js";
import crmAuthLocalRouter from "./crmAuthLocalRoute.js";
import crmGatewayRouter from "./crmGatewayRoute.js";
import crmCustomersAliasRouter from "./crmCustomersAliasRoute.js";
import whatsappRouter from "./whatsappRoute.js";
import messagingIntegrationRouter from "./messagingIntegrationRoute.js";
import messagingDispatchRouter from "./messagingDispatchRoute.js";

const routes = (app) => {
  app.use("/auth", authRouter);
  app.use("/roles", roleRouter);
  app.use("/permissions", permissionRouter);
  app.use("/sessions", loginSessionRouter);
  app.use("/users", panelUserRouter);
  app.use("/user", userRouter);
  app.use("/customers", customerImportRoute);
  app.use("/supplier", supplierRouter);
  app.use("/order", orderRouter);
  app.use("/product", productRouter);
  app.use("/scheduler", schedulerRouter);
  app.use("/income-expance", incomeExpRouter);
  app.use("/supplier-orderdetails", supOrdDetailsRouter);
  app.use("/master", masterRouter);
  app.use("/upload", uploadRouter);
  app.use("/dashboard", dashboardRouter);
  app.use("/coast", coastRouter);
  app.use("/labor-pricing", laborPriceRouter);
  app.use("/diamond-master", diamondMasterRouter);
  app.use("/pricing-products", pricingProductRouter);
  app.use("/partners", partnerRouter);
  app.use("/assets", assetRouter);
  app.use("/targets", targetRouter);
app.use("/mediators", mediatorRouter);
app.use("/payments", paymentRouter);
  app.use("/admin/backup", backupRouter);
  app.use("/employees", employeeRouter);
  app.use("/salary", salaryRouter);
  app.use("/stocks", stockRouter);
  app.use("/crm", crmRouter);
  app.use("/crm", crmCustomersAliasRouter);
  app.use("/crm-auth", crmAuthLocalRouter);
  app.use("/crm-gateway", crmGatewayRouter);
  app.use("/whatsapp", whatsappRouter);
  app.use("/messaging-integrations", messagingIntegrationRouter);
  app.use("/messaging", messagingDispatchRouter);
};

export default routes;
